{
  config,
  lib,
  inputs,
  profile,
  ...
}:

{
  imports = [ inputs.sops-nix.nixosModules.sops ];

  sops = {
    # defaultSopsFile = "${flakeRoot}/secrets/${profile.login}/secrets.yaml";

    # When setting a string to the full path avoids copying the secrets file to the Nix store.
    # However that means that the file has to be deployed to the remote by some other mechanism
    # whenever the configuration is activated remotely. For this reason we instead use a Nix path.
    # In that case Nix includes the encrypted secrets file in the derivation closure forcing it
    # to be in the Nix Store such that can be used for decryption when doing remote activations.
    # inputs.self resolves to the user's own flake — secrets live in the user's
    # private repo, not in dotless, so this is intentional.
    defaultSopsFile = "${inputs.self}/secrets/${profile.login}/secrets.yaml";

    # Avoid "secrets.yaml is not in the Nix store" errors
    # NOTE enable this when using a sring path to the secrets file in the `defaultSopsFile` option
    # validateSopsFiles = false;

    age.sshKeyPaths = [
      "/etc/ssh/ssh_host_ed25519_key" # Generated by `services.openssh.hostKeys` on NixOS
    ]
    ++
      lib.optional (config.users.users ? "${profile.login}")
        "${config.users.users."${profile.login}".home}/.ssh/id_ed25519"; # Key belonging to the profile (also used in Git signing)

    age.generateKey = false; # System shouldn't generate a key under a user directory
  };
}
